# Generated by Django 4.0.3 on 2022-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_notice_returntext_rightwrong_alter_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightwrong',
            name='answer',
        ),
        migrations.AddField(
            model_name='rightwrong',
            name='LipNetResult',
            field=models.CharField(max_length=20, null=True, verbose_name='LipNetResult'),
        ),
        migrations.AddField(
            model_name='rightwrong',
            name='sttResult',
            field=models.CharField(max_length=10, null=True, verbose_name='sttResult'),
        ),
    ]
