# Generated by Django 4.0.3 on 2022-06-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_remove_rightwrong_answer_rightwrong_lipnetresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntext',
            name='LipNetAnswer',
            field=models.CharField(max_length=20, null=True, verbose_name='LipNetText'),
        ),
        migrations.AlterField(
            model_name='returntext',
            name='sttAnswer',
            field=models.CharField(max_length=20, null=True, verbose_name='sttText'),
        ),
    ]
