# Generated by Django 4.0.3 on 2022-06-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_returntext_lipnetanswer_alter_returntext_sttanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightwrong',
            name='presentWord',
            field=models.CharField(max_length=10, null=True, verbose_name='presentWord'),
        ),
    ]
