# Generated by Django 4.0.3 on 2022-06-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_alter_rightwrong_lipnetresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightwrong',
            name='LipNetResult',
            field=models.CharField(max_length=64, null=True, verbose_name='독순결과'),
        ),
        migrations.AlterField(
            model_name='rightwrong',
            name='presentWord',
            field=models.CharField(max_length=64, null=True, verbose_name='제시단어'),
        ),
        migrations.AlterField(
            model_name='rightwrong',
            name='sttResult',
            field=models.CharField(max_length=64, null=True, verbose_name='음성인식결과'),
        ),
    ]
