# Generated by Django 4.0.3 on 2022-06-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_delete_notice_delete_returntext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, null=True, verbose_name='제시단어목록')),
            ],
        ),
        migrations.AlterField(
            model_name='rightwrong',
            name='LipNetResult',
            field=models.CharField(max_length=20, null=True, verbose_name='독순비교결과'),
        ),
        migrations.AlterField(
            model_name='rightwrong',
            name='presentWord',
            field=models.CharField(max_length=20, null=True, verbose_name='제시단어'),
        ),
        migrations.AlterField(
            model_name='rightwrong',
            name='sttResult',
            field=models.CharField(max_length=20, null=True, verbose_name='stt비교결과'),
        ),
    ]
